version: '3.8'

services:
  app:
    build: .
    container_name: devops_task
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devops_task
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Lt*08161554409

  db:
    image: postgres:latest
    container_name: POSTGRES
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devops_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lt*08161554409
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
